---
# Source: covid-tracker/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: covid-tracker-config
  labels:
    helm.sh/chart: covid-tracker-0.1.0
    app.kubernetes.io/name: covid-tracker
    app.kubernetes.io/instance: covid-tracker
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
data:
  SPRING_CRON_SCHEDULE: 0 0 0/6 1/1 * ?
---
# Source: covid-tracker/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: covid-tracker
  annotations:
  labels:
    helm.sh/chart: covid-tracker-0.1.0
    app.kubernetes.io/name: covid-tracker
    app.kubernetes.io/instance: covid-tracker
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  externalTrafficPolicy: Local
  sessionAffinity: None
  ipFamilyPolicy: SingleStack
  ipFamilies: 
    - IPv4
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
      appProtocol: http
  selector:
    app.kubernetes.io/name: covid-tracker
    app.kubernetes.io/instance: covid-tracker
---
# Source: covid-tracker/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-tracker
  labels:
    helm.sh/chart: covid-tracker-0.1.0
    app.kubernetes.io/name: covid-tracker
    app.kubernetes.io/instance: covid-tracker
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: covid-tracker
      app.kubernetes.io/instance: covid-tracker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: covid-tracker
        app.kubernetes.io/instance: covid-tracker
    spec:
      serviceAccountName: default
      securityContext:
        runAsNonRoot: true
        runAsUser: 10101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: covid-tracker
          image: "stevenjdh/covid-tracker:1.0.0"
          imagePullPolicy: Always
          ports:
            - name: actuator
              containerPort: 8081
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          envFrom:
          - configMapRef:
              name: covid-tracker-config
          livenessProbe: 
            failureThreshold: 5
            httpGet:
              path: /actuator/health/liveness
              port: actuator
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe: 
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: actuator
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {}
          volumeMounts:
          - mountPath: /tmp
            name: tmp
      volumes:
      - emptyDir: {}
        name: tmp
      nodeSelector:
        kubernetes.io/os: linux
---
# Source: covid-tracker/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: covid-tracker
  labels:
    helm.sh/chart: covid-tracker-0.1.0
    app.kubernetes.io/name: covid-tracker
    app.kubernetes.io/instance: covid-tracker
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: nginx
  rules:
    - host: "*"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: covid-tracker
                port:
                  number: 80
---
# Source: covid-tracker/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "covid-tracker-test-connection"
  labels:
    helm.sh/chart: covid-tracker-0.1.0
    app.kubernetes.io/name: covid-tracker
    app.kubernetes.io/instance: covid-tracker
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['covid-tracker:80']
  restartPolicy: Never
