{
 "title": "Schema Registry (CFK)",
 "tags": [
  "Strimzi",
  "Kafka",
  "schema",
  "schemaregistry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Kafka Schema Registry servers",
   "type": "stat",
   "description": "Number of Kafka Schema Registry servers",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cp_kafka_schema_registry_jetty_metrics_connections_active{release=~\"$Release\"})"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "description": "Total number of active TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jetty_metrics_connections_active{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "Open Rate",
   "type": "stat",
   "description": "The average rate per second of opened TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jetty_metrics_connections_opened_rate{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "Close Rate",
   "type": "stat",
   "description": "The average rate per second of closed TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cp_kafka_schema_registry_jetty_metrics_connections_closed_rate{release=~\"$Release\"}"
    }
   ]
  }
 ]
}