# This file is part of Strimzi Cluster Helm Chart <https://github.com/StevenJDH/helm-charts>.
# Copyright (C) 2025-2026 Steven Jenkins De Haro.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##########################
## REQUIREMENTS
##########################
# - A Gateway API implementation that supports gateway.networking.k8s.io/v1 TLSRoute resources is installed.
# - A Gateway API Gateway is configured for Kafka traffic and accepts TLSRoutes from the Kafka namespace.
# - DNS records for the bootstrap and per-broker hostnames resolve to the Gateway address.
# - A running Cluster Operator.
#
##########################
## SETUP
##########################
# 1. If using Rancher Desktop, make sure to disable traefik in the configuration since this one is a very old version that doesn't support the Gateway API v1 resources used by Strimzi.
#
# 2. Install the Gateway API CRDs from https://gateway-api.sigs.k8s.io/guides/getting-started/introduction/#installing-gateway-api using the following command or directly as per documentation. This requires kubernetes 1.31+ or the TLSRoute CRD will fail to install.
#       kubectl apply --server-side -f resources/gateway-api-bundle-standard-install_v1.6.1.yaml
#
# 3. Install a more recent version of traefik, which will also install a GatewayClass. For example:
#       helm upgrade --install traefik oci://ghcr.io/traefik/helm/traefik --version 41.3.0 \
#           -f resources/traefik-values.yaml \
#           --namespace traefik \
#           --create-namespace \
#           --atomic
#
# 4. Install a Kafka Gateway with the below command:
#       kubectl apply -f resources/kafka-gateway.yaml
#
# 5. Finally, install Strimzi with this example config using the below. This config assumes Keycloak is installed for OAuth using Ingress Terminated TLS. If not, see example here for that https://github.com/StevenJDH/helm-charts/tree/main/charts/keycloak-stack.
#       helm upgrade --install my-strimzi-cluster stevenjdh/strimzi-cluster --version 0.3.0 \
#           -f accessing-via-gateway-api.yaml \
#           --namespace strimzi \
#           --create-namespace \
#           --atomic
#
##########################
## Testing
##########################
# 1. Download Kafka CLI using the 'Binary download' option from https://kafka.apache.org/community/downloads/#431, and extract the archive.
#
# 2. Copy over the 'kafka-oauth.config' file to the root of the extract Kafka CLI directory where you see the 'bin' folder. Edit any settings that needs updating.
#
# 3. Created a truststore for the Strimzi Cluster CA certificate. Also, include the CA used for Keycloak. Put the truststore.p12 in the same place as the config just copied.
#
# 4. Open a terminal inside the 'resources/kafka-cli-oauth-addon' folder, and run the below command:
#       ./mvnw dependency:copy-dependencies -DoutputDirectory=oauth-deps -DoauthVersion="0.18.0"
#
# 5. The previous command creates a folder called 'oauth-deps' with jar files. Copy just these files, and paste them into the 'libs' folder found in the root of the Kafka CLI directory.
#
# 6. Run the following commands to configure logging and to send some test messages. Use Ctrl+C when finished.
#       export KAFKA_LOG4J_OPTS='-Dlog4j2.configurationFile=config/tools-log4j2.yaml'
#       bin/kafka-console-producer.sh --bootstrap-server oauth-bootstrap.kafka.127.0.0.1.sslip.io:443 \
#           --command-config kafka-oauth.config --topic test-topic
#
# 7. Finally, run this last command to consume the messages just created:
#       bin/kafka-console-consumer.sh --bootstrap-server oauth-bootstrap.kafka.127.0.0.1.sslip.io:443 \
#           --command-config kafka-oauth.config --topic test-topic --from-beginning
#
##########################
## Resources
##########################
# - https://strimzi.io/docs/operators/latest/deploying#proc-accessing-kafka-using-tlsroutes-str
# - https://artifacthub.io/packages/helm/traefik/traefik

kafka:
  config:
    principal.builder.class: io.strimzi.kafka.oauth.server.OAuthKafkaPrincipalBuilder
    # Needed when OAuth protected resources (rsname) are scoped to a specific cluster.
    # The value should match the name of the kafka resource name.
    strimzi.authorization.kafka.cluster.name: my-strimzi-cluster
    strimzi.authorization.client.id: kafka
    strimzi.authorization.token.endpoint.uri: http://my-keycloak-stack-service.keycloak.svc.cluster.local:8080/realms/strimzi/protocol/openid-connect/token
    # Whether authorization decision should be delegated to the 'Simple' authorizer
    # if DENIED by Keycloak Authorization Services policies. Default value is false.
    # Set as true to support both OAuth and mTLS users.
    strimzi.authorization.delegate.to.kafka.acl: "true"
    
    # When empty, disables TLS hostname verification, otherwise, remove this property.
    #strimzi.authorization.ssl.endpoint.identification.algorithm: ""
    
    # Trusted certificates for TLS connection to the Keycloak server when accessing
    # external Keycloak Urls that use https and not signed by trusted CA.
    # strimzi.authorization.ssl.truststore.location: /mnt/keycloak-certs/tls.crt
    # strimzi.authorization.ssl.truststore.type: PEM
    strimzi.authorization.enable.metrics: true
    strimzi.authorization.connect.timeout.seconds: 60
    strimzi.authorization.read.timeout.seconds: 60
    strimzi.authorization.http.retries: 3
    strimzi.authorization.reuse.grants: false
    # Increase grantsRefreshPeriodSeconds to reduce load on Keycloak server.
    # Reference: https://github.com/strimzi/strimzi-kafka-oauth/tree/main#grant-refresh-and-caching
    strimzi.authorization.grants.refresh.period.seconds: 60
    strimzi.authorization.grants.refresh.pool.size: 5
    strimzi.authorization.grants.max.idle.time.seconds: 300
    strimzi.authorization.grants.gc.period.seconds: 300
  template:
    pod:
      volumes: []
    #   - name: keycloak-certs-vol
    #     secret:
    #       secretName: keycloak-certs
    kafkaContainer:
      volumeMounts: []
    #   - name: keycloak-certs-vol
    #     mountPath: /mnt/keycloak-certs
  rackTopology:
    enabled: false
  logging:
    type: inline
    loggers:
      rootLogger.level: "INFO"
      logger.orgapachekafka.level: "INFO"
      logger.kafka.level: "INFO"
      logger.authorizer.level: "INFO"
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9094
      type: internal
      tls: true
      authentication:
        type: tls
      configuration:
        useServiceDnsDomain: true
    - name: externaltls
      port: 9196
      type: tlsroute
      tls: true
      authentication:
        type: tls
      configuration:
        parentRefs:
          - name: kafka-gateway
            kind: Gateway
            group: gateway.networking.k8s.io
            namespace: strimzi
            sectionName: kafka
        bootstrap:
          host: mtls-bootstrap.kafka.127.0.0.1.sslip.io
        hostTemplate: mtls-broker-{nodeId}.kafka.127.0.0.1.sslip.io
        advertisedPortTemplate: "443"
    - name: externaloauth
      port: 9198
      type: tlsroute
      tls: true
      authentication:
        type: custom
        sasl: true
        listenerConfig:
          sasl.enabled.mechanisms: OAUTHBEARER
          oauthbearer.sasl.server.callback.handler.class: io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
          # Trusted certificates for TLS connection to the Keycloak server when accessing
          # external Keycloak Urls that use https and not signed by trusted CA. Add entries
          # below to jaas config if needed.
          #   oauth.ssl.truststore.location="/mnt/keycloak-certs/tls.crt"
          #   oauth.ssl.truststore.type="PEM"
          # An additional check in jaas config that can be used to control who in the realm has access to Kafka.
          #   oauth.custom.claim.check="'kafka-user' in @.realm_access.roles"
          # When empty, disables TLS hostname verification, otherwise, remove this property from jaas config.
          #   oauth.ssl.endpoint.identification.algorithm=""
          oauthbearer.sasl.jaas.config: >-
            org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule
            required unsecuredLoginStringClaim_sub="unused"
            oauth.valid.issuer.uri="https://keycloak.127.0.0.1.sslip.io/realms/strimzi"
            oauth.jwks.endpoint.uri="http://my-keycloak-stack-service.keycloak.svc.cluster.local:8080/realms/strimzi/protocol/openid-connect/certs"
            oauth.username.claim="preferred_username"
            oauth.enable.metrics="true" ;
          connections.max.reauth.ms: 3600000
      configuration:
        parentRefs:
          - name: kafka-gateway
            kind: Gateway
            group: gateway.networking.k8s.io
            namespace: strimzi
            sectionName: kafka
        bootstrap:
          host: oauth-bootstrap.kafka.127.0.0.1.sslip.io
        hostTemplate: oauth-broker-{nodeId}.kafka.127.0.0.1.sslip.io
        advertisedPortTemplate: "443"
  authorization:
    # For a complete authorization example, import the following into Keycloak and adjust as needed:
    # https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/refs/heads/main/examples/security/keycloak-authorization/kafka-authz-realm.json
    type: custom
    authorizerClass: io.strimzi.kafka.oauth.server.authorizer.KeycloakAuthorizer
    # Needed by the Entity Operator to manage ACLs for the KafkaUser resources.
    supportsAdminApi: true
    superUsers:
    - service-account-kafka
    - service-account-test-user
    - CN=test-user
  clusterCa:
    generateSecretOwnerReference: true
  clientsCa:
    generateSecretOwnerReference: true

podMonitor:
  create: false
  labels:
    release: kube-prometheus-stack

scrapeConfigHeadlessServices:
  create: false

prometheusKafkaAlerts:
  create: false

nodePools:
  broker:
    enabled: false
    annotations:
      strimzi.io/next-node-ids: "[0-10]"
  kraft-controller:
    enabled: false
    annotations:
      strimzi.io/next-node-ids: "[11-20]"
  dual-role-broker:
    enabled: true

testResources:
  create: true

k6:
  loadTestScripts:
    create: true
  dashboard:
    enabled: true

crds:
  upgradeJob:
    enabled: true
  deleteJob:
    enabled: true

strimzi-kafka-operator:
  dashboards:
    enabled: true

strimzi-drain-cleaner:
  enabled: false
  certManager:
    create: false
