# This file is part of Strimzi Cluster Helm Chart <https://github.com/StevenJDH/helm-charts>.
# Copyright (C) 2025-2026 Steven Jenkins De Haro.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kafka:
  config:
    principal.builder.class: io.strimzi.kafka.oauth.server.OAuthKafkaPrincipalBuilder
    # Needed when OAuth protected resources (rsname) are scoped to a specific cluster.
    # The value should match the name of the kafka resource name.
    strimzi.authorization.kafka.cluster.name: my-strimzi-cluster
    strimzi.authorization.client.id: kafka
    strimzi.authorization.token.endpoint.uri: http://my-keycloak-stack-service.keycloak.svc.cluster.local:8080/realms/strimzi/protocol/openid-connect/token
    # Whether authorization decision should be delegated to the 'Simple' authorizer
    # if DENIED by Keycloak Authorization Services policies. Default value is false.
    # Set as true to support both OAuth and mTLS users.
    strimzi.authorization.delegate.to.kafka.acl: "true"
    
    # When empty, disables TLS hostname verification, otherwise, remove this property.
    #strimzi.authorization.ssl.endpoint.identification.algorithm: ""
    
    # Trusted certificates for TLS connection to the Keycloak server when accessing
    # external Keycloak Urls that use https and not signed by trusted CA.
    # strimzi.authorization.ssl.truststore.location: /mnt/keycloak-certs/tls.crt
    # strimzi.authorization.ssl.truststore.type: PEM
    strimzi.authorization.enable.metrics: true
    strimzi.authorization.connect.timeout.seconds: 60
    strimzi.authorization.read.timeout.seconds: 60
    strimzi.authorization.http.retries: 3
    strimzi.authorization.reuse.grants: false
    # Increase grantsRefreshPeriodSeconds to reduce load on Keycloak server.
    # Reference: https://github.com/strimzi/strimzi-kafka-oauth/tree/main#grant-refresh-and-caching
    strimzi.authorization.grants.refresh.period.seconds: 60
    strimzi.authorization.grants.refresh.pool.size: 5
    strimzi.authorization.grants.max.idle.time.seconds: 300
    strimzi.authorization.grants.gc.period.seconds: 300
  template:
    pod:
      volumes: []
    #   - name: keycloak-certs-vol
    #     secret:
    #       secretName: keycloak-certs
    kafkaContainer:
      volumeMounts: []
    #   - name: keycloak-certs-vol
    #     mountPath: /mnt/keycloak-certs
  rackTopology:
    enabled: false
  logging:
    type: inline
    loggers:
      rootLogger.level: "INFO"
      logger.orgapachekafka.level: "INFO"
      logger.kafka.level: "INFO"
      logger.authorizer.level: "INFO"
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9094
      type: internal
      tls: true
      authentication:
        type: tls
      configuration:
        useServiceDnsDomain: true
    - name: oauth
      port: 9198
      type: ingress # Deprecated, but still works. Use 'cluster-ip' to provide own solution if needed, or use tlsroute.
      tls: true
      authentication:
        type: custom
        sasl: true
        listenerConfig:
          sasl.enabled.mechanisms: OAUTHBEARER
          oauthbearer.sasl.server.callback.handler.class: io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
          # Trusted certificates for TLS connection to the Keycloak server when accessing
          # external Keycloak Urls that use https and not signed by trusted CA. Add entries
          # below to jaas config if needed.
          #   oauth.ssl.truststore.location="/mnt/keycloak-certs/tls.crt"
          #   oauth.ssl.truststore.type="PEM"
          # An additional check in jaas config that can be used to control who in the realm has access to Kafka.
          #   oauth.custom.claim.check="'kafka-user' in @.realm_access.roles"
          # When empty, disables TLS hostname verification, otherwise, remove this property from jaas config.
          #   oauth.ssl.endpoint.identification.algorithm=""
          oauthbearer.sasl.jaas.config: >-
            org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule
            required unsecuredLoginStringClaim_sub="unused"
            oauth.valid.issuer.uri="https://keycloak.127.0.0.1.sslip.io/realms/strimzi"
            oauth.jwks.endpoint.uri="http://my-keycloak-stack-service.keycloak.svc.cluster.local:8080/realms/strimzi/protocol/openid-connect/certs"
            oauth.username.claim="preferred_username"
            oauth.enable.metrics="true" ;
          connections.max.reauth.ms: 3600000
      configuration:
        class: nginx
        bootstrap:
          host: oauth-bootstrap.kafka.127.0.0.1.sslip.io
        hostTemplate: oauth-broker-{nodeId}.kafka.127.0.0.1.sslip.io
        # Clients need to trust CA extracted with below command or specify a custom cert chain
        # as per below commented out section.
        # openssl s_client -connect oauth-broker-0.kafka.127.0.0.1.sslip.io:443 -servername oauth-broker-0.kafka.127.0.0.1.sslip.io -showcerts
        # kubectl get secret <cluster-name>-cluster-ca-cert -o jsonpath='{.data.ca\.crt}' -n strimzi | base64 -d > ca.crt
        # brokerCertChainAndKey:
        #   # kubectl create secret tls my-tls-secret --cert=path/to/tls.crt --key=path/to/tls.key -n strimzi
        #   secretName: my-tls-secret
        #   certificate: tls.crt
        #   key: tls.key
  authorization:
    # For a complete authorization example, import the following into Keycloak and adjust as needed:
    # https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/refs/heads/main/examples/security/keycloak-authorization/kafka-authz-realm.json
    type: custom
    authorizerClass: io.strimzi.kafka.oauth.server.authorizer.KeycloakAuthorizer
    # Needed by the Entity Operator to manage ACLs for the KafkaUser resources.
    supportsAdminApi: true
    superUsers:
    - service-account-kafka
    - service-account-test-user
    - CN=test-user
  clusterCa:
    generateSecretOwnerReference: true
  clientsCa:
    generateSecretOwnerReference: true

podMonitor:
  create: false
  labels:
    release: kube-prometheus-stack

scrapeConfigHeadlessServices:
  create: false

prometheusKafkaAlerts:
  create: false

nodePools:
  broker:
    enabled: false
    annotations:
      strimzi.io/next-node-ids: "[0-10]"
  kraft-controller:
    enabled: false
    annotations:
      strimzi.io/next-node-ids: "[11-20]"
  dual-role-broker:
    enabled: true

testResources:
  create: true

k6:
  loadTestScripts:
    create: true
  dashboard:
    enabled: true

crds:
  upgradeJob:
    enabled: true
  deleteJob:
    enabled: true

strimzi-kafka-operator:
  dashboards:
    enabled: true

strimzi-drain-cleaner:
  enabled: false
  certManager:
    create: false
