# This file is part of Keycloak Stack Helm Chart <https://github.com/StevenJDH/helm-charts>.
# Copyright (C) 2026 Steven Jenkins De Haro.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

bootstrapAdmin:
  user:
    username: admin
    password: admin

hostname:
  host: "keycloak.127.0.0.1.sslip.io"

devModeEnabled: true

ingress:
  className: traefik

features:
  # Enable the 'scripts' feature if using a Node.js-based mapper like
  # the 'akhq-acl-mapper-script.jar' custom mapper.
  enabled: []
  # - scripts

# This example dynamically adds a custom mapper to the providers folder,
# but there are other approaches to do this. For example, creating custom
# images, mounting folders that already have it, etc.
# Reference: https://www.keycloak.org/server/directory-structure
podTemplate:
  spec:
    initContainers:
      - name: download-custom-providers
        image: curlimages/curl:8.21.0
        command:
          - sh
          - -c
          - |
            set -e
            echo "Starting download for StevenJDH/akhq-acl-mapper..."
            # Replace 'latest/download' in the URL with a specific version like 'download/0.3.0' to pin to a release.
            curl -SsLf https://github.com/StevenJDH/akhq-acl-mapper/releases/latest/download/akhq-acl-mapper.jar \
              -o /providers/akhq-acl-mapper.jar
            echo "Download finished."
        volumeMounts:
          - name: providers
            mountPath: /providers
    containers:
      - name: keycloak
        volumeMounts:
          - name: providers
            mountPath: /opt/keycloak/providers
    volumes:
      - name: providers
        emptyDir: {}

postgresql:
  auth:
    password: password