# This file is part of Keycloak Stack Helm Chart <https://github.com/StevenJDH/helm-charts>.
# Copyright (C) 2026 Steven Jenkins De Haro.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

bootstrapAdmin:
  user:
    username: admin
    password: admin

# See README for how to create certificates to test with.
http:
  # Use this if you already have an existing tls secret for the above hostname.
  tlsSecret: ""
  tls:
    # -- certContent specifies PEM-encoded TLS certificate used to create a TLS Secret when
    # `http.tlsSecret` is not specified. This property is primarily intended for use with Helm's
    # `--set-file` option, but supports inline when using a pipe. Ignored if `http.tlsSecret` is set.
    certContent: ""
    # certContent: |
    #   -----BEGIN CERTIFICATE-----
    #   ...server
    #   -----END CERTIFICATE-----
    #   -----BEGIN CERTIFICATE-----
    #   ...CA
    #   -----END CERTIFICATE-----

    # -- keyContent specifies PEM-encoded TLS private key used to create a TLS Secret when
    # `http.tlsSecret` is not specified. This property is primarily intended for use with Helm's
    # `--set-file` option, but supports inline when using a pipe. Ignored if `http.tlsSecret` is set.
    keyContent: ""
    # keyContent: |
    #   -----BEGIN PRIVATE KEY-----
    #   ...
    #   -----END PRIVATE KEY-----

hostname:
  host: "keycloak.127.0.0.1.sslip.io"

devModeEnabled: false

ingress:
  # When using an ingress controller like traefik that doesn't support
  # TLS passthrough via the ingress resource, set this to false. To test 
  # with traefik, deploy the IngressRouteTCP CR with the following command:
  #   kubectl create -f examples/resources/passthrough-tls-traefik.yaml
  # Note: Update the namespace, service name, hostname if using something 
  # different. It may take a minute for changes to take effect.
  #
  # To check things on the traefik dashboard, use the below command:
  #   kubectl port-forward deployment/traefik 9000:9000 -n kube-system
  # And access the page here: http://localhost:9000/dashboard/#/tcp/routers
  # Note: Always include the slash after dashboard or the main page
  # won't load if going direct.
  enabled: false
  className: traefik

postgresql:
  auth:
    password: "password"