{{/*
This file is part of Strimzi Cluster <https://github.com/StevenJDH/helm-charts>.
Copyright (C) 2025 Steven Jenkins De Haro.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if ((.Values.testResources).create) -}}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: test-user
  labels:
    strimzi.io/cluster: {{ include "shared-library.fullname" . }}
    {{- include "shared-library.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Consumer ACLs for test-topic using any consumer group.
      - resource:
          type: topic
          name: test-topic
          patternType: literal
        operations:
          - Describe
          - Read
        host: "*"
      - resource:
          type: group
          name: test-consumer-group
          patternType: literal
        operations:
          - Read
        host: "*"
      # Producer ACLs for test-topic.
      - resource:
          type: topic
          name: test-topic
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
{{- end -}}