{{/*
This file is part of Keycloak Stack Helm Chart <https://github.com/StevenJDH/helm-charts>.
Copyright (C) 2026 Steven Jenkins De Haro.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- $requiredMsg := include "shared-library.required-msg" . -}}

apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: {{ include "shared-library.fullname" . }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "shared-library.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- /*
  Workaround to handle 0 properly when it is a number or a string.
  Reference: https://github.com/helm/helm/issues/3164 
  */}}
  {{- if not (kindIs "invalid" .Values.instances) }}
  instances: {{ .Values.instances }}
  {{- else }}
  instances: 1
  {{- end }}
  {{- with .Values.image }}
  image: {{ . | quote }}
  {{- end }}
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  startOptimized: {{ .Values.startOptimized }}
  bootstrapAdmin:
    {{- if .Values.bootstrapAdmin.user.username }}
    user:
      secret: {{ template "shared-library.fullname" . }}-secret
    {{- end }}
    {{- if .Values.bootstrapAdmin.service.clientId }}
    service:
      secret: {{ template "shared-library.fullname" . }}-secret
    {{- end }}
  {{- with .Values.admin.tlsSecret }}
  admin:
    tlsSecret: {{ . }}
  {{- end }}
  {{- with .Values.cache.configMapFile }}
  cache:
    configMapFile:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  db:
    vendor: {{ .Values.postgresql.enabled | ternary (.Values.db.vendor | default "postgres") .Values.db.external.vendor }}
    host: {{ .Values.postgresql.enabled | ternary (.Values.db.hostOverride | default (printf "%s-%s.%s.svc.cluster.local" .Release.Name "keycloak-postgresql-hl" .Release.Namespace)) .Values.db.external.host }}
    database: {{ .Values.postgresql.enabled | ternary .Values.postgresql.auth.database .Values.db.external.database }}
    port: {{ .Values.postgresql.enabled | ternary .Values.db.port .Values.db.external.port }}
    usernameSecret:
      name: {{ template "shared-library.fullname" . }}-secret
      key: db-username
    {{- if .Values.postgresql.enabled }}
    passwordSecret:
      name: {{ .Release.Name }}-keycloak-postgresql
      key: postgres-password
    {{- else }}
    passwordSecret:
      name: {{ template "shared-library.fullname" . }}-secret
      key: db-password
    {{- end }}
    schema: {{ .Values.postgresql.enabled | ternary .Values.db.schema .Values.db.external.schema }}
    {{- with .Values.db.poolInitialSize }}
    poolInitialSize: {{ . }}
    {{- end }}
    {{- with .Values.db.poolMinSize }}
    poolMinSize: {{ . }}
    {{- end }}
    {{- with .Values.db.poolMaxSize }}
    poolMaxSize: {{ . }}
    {{- end }}
  transaction:
    xaEnabled: {{ .Values.transaction.xaEnabled }}
  http:
    {{- with .Values.http.labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.http.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    httpEnabled: {{ .Values.devModeEnabled | ternary false .Values.http.httpEnabled }}
    httpPort: {{ .Values.http.httpPort }}
    httpsPort: {{ .Values.http.httpsPort }}
    {{- with .Values.http.serviceName }}
    serviceName: {{ . }}
    {{- end }}
    {{- with .Values.http.serviceHttpPort }}
    serviceHttpPort: {{ . }}
    {{- end }}
    {{- with .Values.http.serviceHttpsPort }}
    serviceHttpsPort: {{ . }}
    {{- end }}
    {{- if and .Values.ingress.enabled (not .Values.ingress.tlsSecret) }}
    {{- with .Values.http.tlsSecret }}
    tlsSecret: {{ . }}
    {{- end }}
    {{- end }}
  hostname:
    hostname: {{ .Values.hostname.host }}
    {{- with .Values.hostname.adminHost }}
    admin: {{ . }}
    {{- end }}
    strict: {{ .Values.devModeEnabled | ternary false .Values.hostname.strict }}
    backchannelDynamic: {{ .Values.hostname.backchannelDynamic }}
  automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
  {{- /* Ensuring not a Passthrough scenario. */}}
  {{- if not (and .Values.http.tlsSecret (not .Values.ingress.tlsSecret)) }}
  {{- with .Values.proxy.headers }}
  proxy:
    headers: {{ . }}
  {{- end }}
  {{- end }}
  ingress:
    enabled: {{ .Values.ingress.enabled }}
    {{- with .Values.ingress.labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.ingress.className }}
    className: {{ . }}
    {{- end }}
    {{- with .Values.ingress.tlsSecret }}
    tlsSecret: {{ . }}
    {{- end }}
  {{- with .Values.extraEnvs }}
  env: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  httpManagement:
    port: {{ .Values.httpManagement.port }}
  {{- with .Values.startupProbe }}
  startupProbe:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.livenessProbe }}
  livenessProbe:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.readinessProbe }}
  readinessProbe:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.import.scheduling }}
  import:
    scheduling:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- with .Values.scheduling }}
  scheduling:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  update:
    {{- with .Values.update.labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.update.scheduling }}
    scheduling:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    strategy: {{ .Values.update.strategy }}
    {{- if eq .Values.update.strategy "Explicit" }}
    revision: {{ .Values.update.revision }}
    {{- end }}
  networkPolicy:
    enabled: {{ .Values.networkPolicy.enabled }}
    {{- with .Values.networkPolicy.http }}
    http:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.networkPolicy.https }}
    https:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.networkPolicy.https }}
    management:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with .Values.truststores }}
  truststores:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  serviceMonitor:
    enabled: {{ .Values.serviceMonitor.enabled }}
    {{- with .Values.serviceMonitor.labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.serviceMonitor.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  tracing:
    enabled: {{ .Values.tracing.enabled }}
    compression: {{ .Values.tracing.compression }}
    endpoint: {{ .Values.tracing.endpoint }}
    protocol: {{ .Values.tracing.protocol }}
    samplerRatio: {{ .Values.tracing.samplerRatio }}
    samplerType: {{ .Values.tracing.samplerType }}
  telemetry:
    enabled: {{ .Values.telemetry.enabled }}
    endpoint: {{ .Values.telemetry.endpoint }}
    serviceName: {{ .Values.telemetry.serviceName | quote }}
    {{- with .Values.telemetry.resourceAttributes }}
    resourceAttributes:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- if or .Values.features.enabled .Values.features.disabled }}
  features:
    {{- with .Values.features.enabled }}
    enabled:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.features.disabled }}
    disabled:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  additionalOptions:
    - name: metrics-enabled
      value: {{ .Values.metrics.enabled | quote }}
    - name: telemetry-metrics-enabled
      value: {{ .Values.telemetry.enabled | quote }}
    {{- with .Values.additionalOptions }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.podTemplate }}
  unsupported:
    podTemplate:
      {{- toYaml . | nindent 6 }}
  {{- end }}