---
# Source: aksupport/templates/cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aksupport
  labels:
    helm.sh/chart: aksupport-0.1.0
    app.kubernetes.io/name: aksupport
    app.kubernetes.io/instance: aksupport
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  jobTemplate:
    metadata:
      labels:
        helm.sh/chart: aksupport-0.1.0
        app.kubernetes.io/name: aksupport
        app.kubernetes.io/instance: aksupport
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      completions: 1
      backoffLimit: 0
      activeDeadlineSeconds: 120
      template:
        metadata:
          labels:
            helm.sh/chart: aksupport-0.1.0
            app.kubernetes.io/name: aksupport
            app.kubernetes.io/instance: aksupport
            app.kubernetes.io/version: "1.0.0"
            app.kubernetes.io/managed-by: Helm
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 10101
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: aksupport
            image: "public.ecr.aws/stevenjdh/aksupport:1.0.0"
            imagePullPolicy: Always
            env:
            - name: AZMON_COLLECT_ENV # Required to prevent sensitive data leaking to Azure Monitor Logs.
              value: "FALSE"
            envFrom:
            - configMapRef:
                name: aksupport-config
            - secretRef:
                name: aksupport-secret
            volumeMounts:
            - mountPath: /tmp
              name: tmp
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
          volumes:
          - emptyDir: {}
            name: tmp
          restartPolicy: Never
        nodeSelector:
          kubernetes.io/os: linux
  schedule: '0 8 * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
