---
# Source: aksupport/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aksupport-secret
  labels:
    helm.sh/chart: aksupport-1.1.0
    app.kubernetes.io/name: aksupport
    app.kubernetes.io/instance: aksupport
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  namespace: default
type: Opaque
data:
---
# Source: aksupport/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aksupport-config
  labels:
    helm.sh/chart: aksupport-1.1.0
    app.kubernetes.io/name: aksupport
    app.kubernetes.io/instance: aksupport
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  namespace: default
data:
  AVATAR_IMAGE_URL: "https://raw.githubusercontent.com/StevenJDH/AKSupport/main/Avatars/aksupport-256x256-transparent-bg.png"
---
# Source: aksupport/templates/cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aksupport
  labels:
    helm.sh/chart: aksupport-1.1.0
    app.kubernetes.io/name: aksupport
    app.kubernetes.io/instance: aksupport
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  namespace: default
spec:
  jobTemplate:
    metadata:
      labels:
        helm.sh/chart: aksupport-1.1.0
        app.kubernetes.io/name: aksupport
        app.kubernetes.io/instance: aksupport
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      completions: 1
      backoffLimit: 0
      activeDeadlineSeconds: 120
      template:
        metadata:
          labels:
            helm.sh/chart: aksupport-1.1.0
            app.kubernetes.io/name: aksupport
            app.kubernetes.io/instance: aksupport
            app.kubernetes.io/version: "1.0.0"
            app.kubernetes.io/managed-by: Helm
        spec:
          serviceAccountName: default
          securityContext:
            runAsNonRoot: true
            runAsUser: 10101
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: aksupport-job
            image: "stevenjdh/aksupport:1.0.0"
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
            env:
              - name: AZMON_COLLECT_ENV
                value: "FALSE"
            envFrom:
            - configMapRef:
                name: aksupport-config
            - secretRef:
                name: aksupport-secret
            volumeMounts:
              - mountPath: /tmp
                name: tmp
          volumes:
            - emptyDir: {}
              name: tmp
          restartPolicy: Never
          nodeSelector:
            kubernetes.io/os: linux
  schedule: '0 8 * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
