# This file is part of Keycloak Operator Helm Chart <https://github.com/StevenJDH/helm-charts>.
# Copyright (C) 2026 Steven Jenkins De Haro.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -- replicaCount is the number of pod instances created by the Deployment owned ReplicaSet to
# increase availability when set to more than one.
replicaCount: 1

image:
  # -- repository holding the container image.
  repository: "quay.io/keycloak/keycloak-operator"
  # -- pullPolicy is the strategy for pulling images from a registry.
  pullPolicy: Always
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullSecret:
    # @ignored. registry is the private docker container registry for pulling images.
    registry: "index.docker.io/v1/"
    # -- username is the Docker username associated with the password.
    username: ""
    # -- password is the Docker password associated with the username with pull rights.
    password: ""

# -- Override for chart name in helm common labels.
nameOverride: ""
# -- Override for generated resource names.
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created.
  create: true
  # -- annotations to be added to the Service Account resource.
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

# -- annotations to be added to the Deployment resource.
annotations: {}

# -- podAnnotations are the annotations to be added to the deployment pods.
podAnnotations: {}

# -- restartPolicy defines how a pod will automatically repair itself when a problem arises.
# Reference [Container restart policy](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy).
restartPolicy: Always

# -- The update strategy to apply to the Deployment resource.
updateStrategy: {}
  # rollingUpdate:
  #   maxUnavailable: 1
  # type: RollingUpdate

# -- command corresponds to the entrypoint in some container images that can be overridden or used to run shell commands.
command: []

# -- Additional command line arguments to pass to the container.
extraArgs: []
# - --arg1
# - value1
# - --arg2
# - value2

watchAllNamespacesFor:
  # -- keycloak is for indicating whether or not Keycloak resources will be watched
  # in all namespaces.
  keycloak: false
  # -- keycloakRealmImport is for indicating whether or not KeycloakRealmImport
  # resources will be watched in all namespaces.
  keycloakRealmImport: false
  # -- keycloakOIDCClient is for indicating whether or not KeycloakOIDCClient
  # resources will be watched in all namespaces.
  keycloakOIDCClient: false
  # -- keycloakSAMLClient is for indicating whether or not KeycloakSAMLClient
  # resources will be watched in all namespaces.
  keycloakSAMLClient: false

# @ignored. Additional environment variables to set.
extraEnvs:
  - name: KUBERNETES_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace

# @ignored
podSecurityContext: {}
  # runAsNonRoot: true
  # runAsUser: 10101
  # seccompProfile:
  #   type: RuntimeDefault

# @ignored
securityContext: {}
  # readOnlyRootFilesystem: false
  # allowPrivilegeEscalation: false
  # capabilities:
  #   drop:
  #   - ALL

# -- priorityClassName is the name of the PriorityClass resource that indicates the
# importance of a Pod relative to other Pods. If a Pod cannot be scheduled, the
# scheduler tries to preempt (evict) lower priority Pods to make scheduling of the
# pending Pod possible.
# Reference [Pod Priority and Preemption](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption).
priorityClassName: ""

# @ignored. containerPort is the port or ports that the container listens on.
containerPorts:
  http: 8080

# @ignored. Startup, Liveness and readiness probes. Liveness probes do not wait
# for readiness probes to succeed. If you want to wait before executing a liveness
# probe you should use initialDelaySeconds or a startupProbe.
# Reference [Configure Liveness, Readiness and Startup Probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes).
health:
  startupProbe:
    failureThreshold: 3
    httpGet:
      path: /q/health/started
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /q/health/live
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /q/health/ready
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10

# -- Additional volumeMounts for the main container.
extraVolumeMounts: []
# - name: example-volume
#   mountPath: /share/example

# -- Additional volumes for the pod.
extraVolumes: []
# - name: example-volume
#   emptyDir: {}

# -- Containers, which are run before the app containers are started.
extraInitContainers: []
# - name: init-myservice
#   image: busybox
#   command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']

service:
  # -- type specifies what kind of Service resource to create.
  type: ClusterIP
  # @ignored
  port: 80
  # @ignored
  targetPort: 8080
  # @ignored
  nodePort: 32080
  # -- appProtocol overrides annotations in a service resource that were used for setting a backend protocol. In AWS for example,
  # `service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http`. See the following GitHub issue for more details
  # [kubernetes/kubernetes#40244](https://github.com/kubernetes/kubernetes/issues/40244). Will be ignored for Kubernetes versions
  # older than 1.20.
  appProtocol: true
  # -- annotations to be added to the Service resource.
  annotations: {}
  # -- ipFamilyPolicy represents the dual-stack-ness requested or required by this Service. Possible values are SingleStack, PreferDualStack or RequireDualStack.
  # The ipFamilies and clusterIPs fields depend on the value of this field.
  # Reference [IPv4/IPv6 dual-stack](https://kubernetes.io/docs/concepts/services-networking/dual-stack).
  ipFamilyPolicy: "SingleStack"
  # -- ipFamilies is a list of IP families (e.g. IPv4, IPv6) assigned to a service. This field is usually assigned automatically
  # based on cluster configuration and the ipFamilyPolicy field. [IPv4/IPv6 dual-stack](https://kubernetes.io/docs/concepts/services-networking/dual-stack).
  ipFamilies:
  - IPv4

# @ignored. Optionally request and limit how much CPU and memory (RAM) the container needs.
# Reference [Resource Management for Pods and Containers](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers).
resources:
  limits:
    cpu: 700m
    memory: 450Mi
  requests:
    cpu: 300m
    memory: 450Mi

# -- configMap is used to store non-confidential data in key-value pairs. Quoting is required if the value is 0.
# The `RELATED_IMAGE_KEYCLOAK` and `relatedImageKeycloak` values are reserved keys and should not be used.
# @default -- `{}`
configMap:
  # @ignored. The Keycloak Operator image only supports the Keycloak version it targets.
  relatedImageKeycloak: quay.io/keycloak/keycloak:26.7.0

# -- nodeSelector is the simplest way to constrain Pods to nodes with specific labels. Use affinity for more advance options.
# Reference [Assigning Pods to Nodes](https://kubernetes.io/docs/user-guide/node-selection).
nodeSelector:
  kubernetes.io/os: linux

# -- affinity for pod scheduling.
# Reference [Assign Pods to Nodes using Node Affinity](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity).
affinity: {}
  # podAntiAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #   - labelSelector:
  #       matchExpressions:
  #       - key: app
  #         operator: In
  #         values:
  #         - app-name
  #     topologyKey: "kubernetes.io/hostname"

# -- tolerations allow the scheduler to schedule pods onto nodes with matching taints.
# Reference [Taints and Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration).
tolerations: []
# - key: "key"
#   operator: "Equal|Exists"
#   value: "value"
#   effect: "NoSchedule|PreferNoSchedule|NoExecute"