---
# Source: aws-cwl-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-cwl-exporter
  annotations:
    eks.amazonaws.com/audience: "sts.amazonaws.com"
    eks.amazonaws.com/role-arn: ""
    eks.amazonaws.com/sts-regional-endpoints: "true"
    eks.amazonaws.com/token-expiration: "86400"
  labels:
    helm.sh/chart: aws-cwl-exporter-0.1.1
    app.kubernetes.io/name: aws-cwl-exporter
    app.kubernetes.io/instance: aws-cwl-exporter
    app.kubernetes.io/version: "2.9.4"
    app.kubernetes.io/managed-by: Helm
---
# Source: aws-cwl-exporter/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-cwl-exporter-config
  labels:
    helm.sh/chart: aws-cwl-exporter-0.1.1
    app.kubernetes.io/name: aws-cwl-exporter
    app.kubernetes.io/instance: aws-cwl-exporter
    app.kubernetes.io/version: "2.9.4"
    app.kubernetes.io/managed-by: Helm
data:
  EXPORT_PERIOD: hourly
  EXPORT_PREFIX: export-task-output
---
# Source: aws-cwl-exporter/templates/cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-cwl-exporter
  labels:
    helm.sh/chart: aws-cwl-exporter-0.1.1
    app.kubernetes.io/name: aws-cwl-exporter
    app.kubernetes.io/instance: aws-cwl-exporter
    app.kubernetes.io/version: "2.9.4"
    app.kubernetes.io/managed-by: Helm
spec:
  jobTemplate:
    metadata:
      labels:
        helm.sh/chart: aws-cwl-exporter-0.1.1
        app.kubernetes.io/name: aws-cwl-exporter
        app.kubernetes.io/instance: aws-cwl-exporter
        app.kubernetes.io/version: "2.9.4"
        app.kubernetes.io/managed-by: Helm
    spec:
      completions: 1
      backoffLimit: 0
      activeDeadlineSeconds: 120
      template:
        metadata:
          labels:
            helm.sh/chart: aws-cwl-exporter-0.1.1
            app.kubernetes.io/name: aws-cwl-exporter
            app.kubernetes.io/instance: aws-cwl-exporter
            app.kubernetes.io/version: "2.9.4"
            app.kubernetes.io/managed-by: Helm
        spec:
          serviceAccountName: aws-cwl-exporter
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: aws-cwl-exporter
            image: "stevenjdh/aws-cwl-exporter:2.9.4"
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
            envFrom:
            - configMapRef:
                name: aws-cwl-exporter-config
            resources:
              {}
            volumeMounts:
            - mountPath: /tmp
              name: tmp
          volumes:
          - emptyDir: {}
            name: tmp
          restartPolicy: Never
          nodeSelector:
            kubernetes.io/os: linux
  schedule: '5 * * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
