{{/*
This file is part of Shared Library Helm Chart <https://github.com/StevenJDH/helm-charts>.
Copyright (C) 2023-2026 Steven Jenkins De Haro.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{/*
CRD upgrade orchestration.

Expected input:

  include "shared-library.crd-upgrade" (dict
    "context" .
    "config" .Values.crds
  )
*/}}
{{- define "shared-library.crd-upgrade" -}}
{{- $config := .config  -}}
{{- if $config.upgradeJob.enabled -}}
{{ include "shared-library._crd-upgrade-configmap" . }}
---
{{ include "shared-library._crd-upgrade-serviceaccount" . }}
---
{{ include "shared-library._crd-upgrade-clusterrole" . }}
---
{{ include "shared-library._crd-upgrade-clusterrolebinding" . }}
---
{{ include "shared-library._crd-upgrade-job" . }}
{{- end }}
{{- end -}}