name: 'Lint and Test Charts'

on: 
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch: # Run workflow manually through the Github Actions Workflow page directly.

jobs:
  lint-test:
    runs-on: ubuntu-latest
    # Map a step output to a job output.
    outputs:
      list-changed: ${{ steps.list-changed.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        # Full version for action needs to be specified.
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --print-config --config ct.yaml

  kind-lint-test:
    if: needs.lint-test.outputs.list-changed == 'true'
    name: Deploy to Kubernetes ${{ matrix.kubernetesVersion }}
    needs: lint-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetesVersion: [v1.19.16, v1.24.6, v1.25.2]
        include:
        # Images: https://github.com/kubernetes-sigs/kind/releases
        - kubernetesVersion: v1.19.16
          kindImage: kindest/node:v1.19.16@sha256:a146f9819fece706b337d34125bbd5cb8ae4d25558427bf2fa3ee8ad231236f2
        - kubernetesVersion: v1.24.6
          kindImage: kindest/node:v1.24.6@sha256:97e8d00bc37a7598a0b32d1fabd155a96355c49fa0d4d4790aab0f161bf31be1
        - kubernetesVersion: v1.25.2
          kindImage: kindest/node:v1.25.2@sha256:9be91e9e9cdf116809841fc77ebdb8845443c4c72fe5218f3ae9eb57fdb4bace
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        # Full version for action needs to be specified.
        uses: helm/chart-testing-action@v2.2.1
        
      - name: Create kind cluster ${{ matrix.kubernetesVersion }}
        uses: helm/kind-action@v1
        with:
          node_image: ${{ matrix.kindImage }}
          kubectl_version: ${{ matrix.kubernetesVersion }}
          cluster_name: chart-testing

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml