name: 'Lint and Test Charts'

on: 
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch: # Run workflow manually through the Github Actions Workflow page directly.

jobs:
  lint-test:
    runs-on: ubuntu-latest
    # Map a step output to a job output.
    outputs:
      list-changed: ${{ steps.list-changed.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Set up chart-testing
        # Full version for action needs to be specified.
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --print-config --config ct.yaml

  kind-lint-test:
    if: needs.lint-test.outputs.list-changed == 'true'
    name: Deploy to Kubernetes ${{ matrix.kubernetesVersion }}
    needs: lint-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetesVersion: [v1.19.16, v1.24.17, v1.29.1]
        include:
        # Images: https://github.com/kubernetes-sigs/kind/releases
        - kubernetesVersion: v1.19.16
          kindImage: kindest/node:v1.19.16@sha256:a146f9819fece706b337d34125bbd5cb8ae4d25558427bf2fa3ee8ad231236f2
        - kubernetesVersion: v1.24.17
          kindImage: kindest/node:v1.24.17@sha256:ea292d57ec5dd0e2f3f5a2d77efa246ac883c051ff80e887109fabefbd3125c7
        - kubernetesVersion: v1.29.1
          kindImage: kindest/node:v1.29.1@sha256:a0cc28af37cf39b019e2b448c54d1a3f789de32536cb5a5db61a49623e527144
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Set up chart-testing
        # Full version for action needs to be specified.
        uses: helm/chart-testing-action@v2.6.1
        
      - name: Create kind cluster ${{ matrix.kubernetesVersion }}
        uses: helm/kind-action@v1
        with:
          node_image: ${{ matrix.kindImage }}
          kubectl_version: ${{ matrix.kubernetesVersion }}
          cluster_name: chart-testing

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml