name: 'Lint and Test Charts'

on: 
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch: # Run workflow manually through the Github Actions Workflow page directly.

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        # Full version for action needs to be specified.
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --print-config --config ct.yaml

      - name: Create kind cluster v1.19.16
        uses: helm/kind-action@v1
        if: steps.list-changed.outputs.changed == 'true'
        with:
          # Images: https://github.com/kubernetes-sigs/kind/releases
          node_image: kindest/node:v1.19.16@sha256:d9c819e8668de8d5030708e484a9fdff44d95ec4675d136ef0a0a584e587f65c
          kubectl_version: v1.19.16
          cluster_name: chart-testing-1-19-16

      - name: Run chart-testing (install) v1.19.16
        run: ct install --config ct.yaml

      - name: Create kind cluster v1.24.0
        uses: helm/kind-action@v1
        if: steps.list-changed.outputs.changed == 'true'
        with:
          # Images: https://github.com/kubernetes-sigs/kind/releases
          node_image: kindest/node:v1.24.0@sha256:406fd86d48eaf4c04c7280cd1d2ca1d61e7d0d61ddef0125cb097bc7b82ed6a1
          kubectl_version: v1.24.0
          cluster_name: chart-testing-1-24-0

      - name: Run chart-testing (install) v1.24.0
        run: ct install --config ct.yaml